language: node_js
node_js: '10'
script:
  - npm run build
  - travis_retry npm run travis
os:
  - linux
dist: xenial
env:
  - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
cache:
  directories:
    - dist
    - node_modules
jobs:
  include:
    - env: BROWSER=mac-chrome-latest
    - env: BROWSER=mac-safari-latest
