language: node_js
node_js: '10'
script:
  - npm run build
  - travis_retry npm run travis
os:
  - linux
dist: xenial
cache:
  directories:
    - node_modules
jobs:
  include:
    - env: BROWSER=mac-chrome-latest
    - env: BROWSER=mac-firefox-latest
    - env: BROWSER=mac-safari-latest
    - env: BROWSER=windows-chrome-latest
    - env: BROWSER=windows-firefox-latest
    - env: BROWSER=windows-edge-latest
    - env: BROWSER=ios-latest
    - env: BROWSER=android-latest
